# Generated by Django 4.2.3 on 2023-12-17 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalticketreport',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical ticket report', 'verbose_name_plural': 'historical ticket reports'},
        ),
        migrations.AlterField(
            model_name='historicalticketreport',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
