# Generated by Django 4.2.3 on 2023-12-17 18:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_externaluser_alter_campus_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=15)),
                ('rut', models.CharField(max_length=9, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Teacher',
                'verbose_name_plural': 'Teachers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Key',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('prestada', models.BooleanField(default=False)),
                ('estado_llave', models.BooleanField(default=True, verbose_name='Estado llave')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.room')),
            ],
            options={
                'verbose_name': 'Key',
                'verbose_name_plural': 'Keys',
                'ordering': ['room'],
            },
        ),
        migrations.CreateModel(
            name='BorrowedKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_entrega', models.DateTimeField(default=django.utils.timezone.now)),
                ('key_devolucion', models.DateTimeField(blank=True, null=True)),
                ('fecha_entraga', models.DateField(auto_now=True, verbose_name='Fecha de entrega')),
                ('llave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keymonitor.key')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keymonitor.teacher')),
            ],
            options={
                'verbose_name': 'Entrega',
                'verbose_name_plural': 'Entregas',
                'ordering': ['profesor'],
            },
        ),
    ]
